project:
  type: website

website:
  title: "Simulation Models in Industrial Engineering"
      
  sidebar:
    style: "floating"
    search: true
    contents:
      - text: "Overview"
        href: index.qmd
      - section: "Tutorials"
        contents:
          - text: "#1 Simulations Overview (Wind Turbine Repair)"
            href: recitations/R1_turbine_repair.qmd
          - text: "#2 Fitting Distributions (Baggage Handling System)"
            href: recitations/R2_baggage_handling_system.qmd
          - text: "#3 Queuing and Animations (Amazon Returns)"
            href: recitations/R3_animations.qmd
          - text: "#4 Check on Learning"
            href: recitations/R4_azimuth_check.qmd
          - text: "#5 Queuing using Simmer"
            href: recitations/R5_simmer1.qmd          
          - text: "#6 Custom Distributions & Reliability (NJT)"
            href: recitations/R6_custom_dists.qmd
          - text: "#7 More Complex Queues with Simmer (MVC)"
            href: recitations/R7_simmer2.qmd
          - text: "#8 Getting Started with Gas Station Modeling"
            href: recitations/R8_gas_station_template.qmd
      - section: "Homework Solutions"
        contents:
          - text: "Homework 1"
            href: solutions/HW1_solution.qmd
          - text: "Homework 2"
            href: solutions/HW2_solution.qmd
          - text: "Homework 3"
            href: solutions/HW3_solution.qmd
          
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/dmoored4/Sim_Recitation_Sp2025
          
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



