project:
  type: website

website:
  title: "Simulation Models in Industrial Engineering"
      
  sidebar:
    style: "floating"
    search: true
    contents:
      - text: "Overview"
        href: index.qmd
      - section: "Tutorials"
        contents:
          - text: "Recitation #1"
            href: recitations/R1_turbine_repair.qmd
          - text: "Recitation #2"
            href: recitations/R2_baggage_handling_system.qmd
          - text: "Rectiation #3"
            href: recitations/R3_animations.qmd
          - text: "Recitation #4"
            href: recitations/R4_azimuth_check.qmd
          - text: "Recitation #5"
            href: recitations/R5_simmer1.qmd          
          - text: "Recitation #6"
            href: recitations/R6_custom_dists.qmd
          - text: "Recitation #7"
            href: recitations/R7_simmer2.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/dmoored4/Sim_Recitation_Sp2025
          
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



