project:
  type: website

website:
  title: "Simulation Models in Industrial Engineering"
      
  sidebar:
    style: "floating"
    search: true
    contents:
      - text: "Overview"
        href: index.qmd
      - section: "Tutorials"
        contents:
          - text: "Recitation #1"
            href: recitations/R1_turbine_repair.qmd
          - text: "Recitation #2"
            href: recitations/R2_baggage_handling_system.qmd
          - text: "Rectiation #3"
            href: recitations/R3_animations.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/dmoored4/Sim_Recitation_Sp2025
          
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



